stages:
  - build
  - test
  - package
  - deploy 

# check:
#   stage: .pre
#   script:
#     - ls -al

# clean:
#   stage: .post
#   script:
#     - rm -rf *

build:
  stage: build
  image: node:21
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo "test"

package:
  stage: package
  script:
    - echo "package"

build image:
  stage: package
  script:
    - echo "build image"

deploy:
  stage: deploy
  script:
    - echo "deploy"